# SwiftLint Configuration for FolderCleaner

disabled_rules:
  - trailing_whitespace # Handled by Xcode

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - .build
  - .swiftpm
  - FolderCleaner.xcodeproj
  - build
  - DerivedData
  - Pods
  - vendor
  - "*/Localizable.xcstrings"

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
  excluded:
    - id
    - x
    - y

reporter: "xcode"
